#!/usr/bin/env python
"""Generate short sanity-check rollout configs from the 8 rMOM6 training configs.

Each output is a verbatim copy of its training config with only ``inference`` and ``pbs``
rewritten. Deriving them from the training config (rather than maintaining a parallel set of
hand-written rollout YAMLs) is the point: preblocks/postblocks/model/scaler paths are then
guaranteed to match what the checkpoint was actually trained with. The pre-existing
config/rollout/*.yml files predate the input-normalization fix and still list only the 5
prognostics under preblocks.normalize, which would feed raw deptho to a model trained on
normalized inputs.

Usage::

    python scripts/make_rmom6_sanity_rollouts.py                 # 60 days from 2018-01-01
    python scripts/make_rmom6_sanity_rollouts.py --days 30
"""

from __future__ import annotations

import argparse
import glob
import os

import yaml

REPO = "/glade/work/ajanney/RegionalEmulation_v2/miles-credit-regional"
TRAIN_GLOB = os.path.join(REPO, "config", "rmom6_regional_*_full.yml")
OUT_DIR = os.path.join(REPO, "config", "rollout")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--days", type=int, default=60, help="Forecast length in daily steps.")
    ap.add_argument(
        "--init-time",
        default="2018-01-01 12:00:00",
        help="Init time. Default is the first out-of-sample day (train ends 2017-12-31).",
    )
    ap.add_argument("--suffix", default="sanity", help="Tag for the output config and rollout subdir.")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    configs = sorted(glob.glob(TRAIN_GLOB))
    if len(configs) != 8:
        raise SystemExit(f"expected 8 training configs, found {len(configs)}")

    for path in configs:
        conf = yaml.safe_load(open(path))
        # tag: e.g. "levelwise_singlestep_notendency"
        tag = os.path.basename(path).replace("rmom6_regional_", "").replace("_full.yml", "")

        # Sanity: the fix must be present, or the rollout is meaningless.
        n_norm = len(conf["preblocks"]["per_step"]["normalize"]["args"]["variables"])
        if n_norm != 11:
            raise SystemExit(f"{tag}: preblocks.normalize lists {n_norm} vars, expected 11 (input-normalization fix)")

        save_dir = f"{conf['save_loc']}/rollout_{args.suffix}_{args.days}d"
        conf["inference"] = {
            "run_mode": "single",
            "mode": "none",
            "save_forecast": save_dir,
            "single_forecast": {
                "forecast_length": f"{args.days}d",
                "start_datetime": args.init_time,
            },
            "output": {
                "format": "netcdf",
                "output_interval": None,
                "group_by": "full",
                "variables": None,
                "metadata": None,
                "encoding": {"dtype": "float32", "zlib": True, "complevel": 4},
            },
        }
        # Single GPU: rollout is sequential in time, so extra ranks only help across init
        # times and there is exactly one here.
        conf["pbs"] = {
            "conda": "miles-credit-derecho",
            "project": conf.get("pbs", {}).get("project", "p93300012"),
            "job_name": f"roll_{tag}",
            "walltime": "01:00:00",
            "nodes": 1,
            "ncpus": 8,
            "ngpus": 1,
            "mem": "64GB",
            "queue": "main",
        }

        out = os.path.join(OUT_DIR, f"rmom6_{tag}_{args.suffix}.yml")
        with open(out, "w") as f:
            f.write(f"# GENERATED by scripts/make_rmom6_sanity_rollouts.py from {os.path.basename(path)}\n")
            f.write(f"# {args.days}-day rollout from {args.init_time}. Do not hand-edit; regenerate instead.\n")
            yaml.dump(conf, f, sort_keys=False, default_flow_style=False, width=120)
        print(f"wrote {out}\n      -> {save_dir}")


if __name__ == "__main__":
    main()
