"""Stamp rMOM6 configs with the known issues that apply to each of them.

Every rMOM6 config predates the fixes in commit 396bf0f0. Most of them are not *broken* by that
-- ``masked_fill_nan`` is unset everywhere, so they inherit the corrected code default -- but each
carries some combination of live issues and invalidated history, and which ones depend on the
config. This writes that combination into a header block so it is visible at the point of use
rather than only in RMOM6_FIXES_2026-08-17.md.

Idempotent: an existing block is replaced, so re-run it after the underlying facts change.

    python scripts/mark_rmom6_config_status.py --dry-run
    python scripts/mark_rmom6_config_status.py
    python scripts/mark_rmom6_config_status.py --strip      # remove the blocks again
"""

import argparse
import glob
import os

import yaml

BEGIN = "# >>> rmom6-status"
END = "# <<< rmom6-status"
REF = "RMOM6_FIXES_2026-08-17.md"

TARGETS = ["config/rmom6_regional_*.yml", "config/rollout/*.yml"]


def issues(path: str, conf: dict) -> list[str]:
    """The issues that apply to this config, most consequential first."""
    out = []
    pre = (conf.get("preblocks") or {}).get("per_step", {}) or {}
    post = (conf.get("postblocks") or {}).get("per_step", {}) or {}
    trainer = conf.get("trainer", {}) or {}
    loss = conf.get("loss", {}) or {}
    data = conf.get("data", {}) or {}

    forecast_len = trainer.get("forecast_len", data.get("forecast_len")) or 1
    is_rollout = "config/rollout/" in path
    has_wet_mask = any(isinstance(v, dict) and v.get("type") == "ocean_wet_mask" for v in post.values())

    norm = [
        v
        for v in pre.values()
        if isinstance(v, dict) and v.get("type") in ("bridgescaler_transform", "pointwise_scaler")
    ]
    stats = (
        (norm[0].get("args", {}).get("scaler_path") or norm[0].get("args", {}).get("stats_path") or "") if norm else ""
    )
    is_xi = "xi" in os.path.basename(stats)

    if forecast_len > 1 and has_wet_mask:
        out.append(
            "[07] Any result produced with this config BEFORE 396bf0f0 is invalid, not merely "
            "undertrained. ocean_wet_mask zeroed land in physical space, so rollout step 2 saw "
            "(0-mu)/sigma there. All four multistep arms reached anomaly correlation ~0. The "
            "config itself is fine -- masked_fill_nan is unset and now defaults to True."
        )
    if forecast_len > 1 and not is_rollout:
        out.append(
            "[06] learning_rate must be re-tuned. The multistep gradient was a sum over rollout "
            "steps while the logged loss was a mean; 396bf0f0 divides by len(backprop_on_timestep), "
            f"which cuts the effective step size by ~{forecast_len}x at this forecast_len."
        )
    if is_xi:
        out.append(
            "[open-1] xi/tendency normalization puts 99.86% of the MSE on 14 of 101 channels "
            "(thetao/so below 1000 m); the 50 velocity channels get 0.00%. This arm is not "
            "measuring what the experiment grid was designed to measure."
        )
    if str(trainer.get("grad_max_norm", "")).lower() == "dynamic":
        out.append(
            "[open-2] grad_max_norm: dynamic performs NO clipping -- it clips to the gradient's "
            "own norm and torch clamps the coefficient at 1.0. Set a real value (1.0 is the usual "
            "starting point)."
        )
    if not is_rollout and not loss.get("mask_missing_targets"):
        out.append(
            "[open-4] loss.mask_missing_targets is off, so the loss is averaged over the full "
            "grid. Land is 50.75% of this domain and is a constant 0 in both y and y_pred, so "
            "roughly half the loss budget is spent fitting a constant."
        )
    if is_rollout:
        out.append(
            "[rollout] Checkpoints trained before 396bf0f0 carry the defects above. Re-run the "
            "training arm before drawing conclusions from a rollout scored against it."
        )
    return out


def block(items: list[str]) -> str:
    lines = [
        BEGIN,
        "# STATUS 2026-08-17 -- this config predates the fixes in commit 396bf0f0.",
        f"# Generated by scripts/mark_rmom6_config_status.py. Details: {REF}",
        "#",
    ]
    for it in items:
        words, line, first = it.split(), "", True
        for w in words:
            candidate = f"{line} {w}".strip()
            if len(candidate) > 94:
                lines.append(f"#   {line}" if first else f"#       {line}")
                first, line = False, w
            else:
                line = candidate
        lines.append(f"#   {line}" if first else f"#       {line}")
        lines.append("#")
    lines.append(END)
    return "\n".join(lines) + "\n"


def strip_block(text: str) -> str:
    if BEGIN not in text:
        return text
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + tail.lstrip("\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--strip", action="store_true", help="Remove the blocks instead of writing them.")
    args = ap.parse_args()

    paths = sorted(p for pat in TARGETS for p in glob.glob(pat))
    for path in paths:
        text = strip_block(open(path).read())
        if args.strip:
            if not args.dry_run:
                open(path, "w").write(text)
            print(f"  stripped  {path}")
            continue

        items = issues(path, yaml.safe_load(text))
        if not items:
            if not args.dry_run:
                open(path, "w").write(text)
            print(f"  clean     {path}")
            continue
        if not args.dry_run:
            open(path, "w").write(block(items) + text)
        tags = " ".join(i.split("]")[0] + "]" for i in items)
        print(f"  {len(items)} issue(s) {path}\n              {tags}")

    print(f"\n{len(paths)} config(s) processed.")


if __name__ == "__main__":
    main()
